'use client';

import { useState, type FormEvent } from 'react';
import { CheckCircle2 } from 'lucide-react';
import { track } from '@/lib/track';

const CONTACT_METHODS = ['Email', 'Telegram', 'X / Twitter', 'Other'] as const;
type ContactMethod = (typeof CONTACT_METHODS)[number];

type Errors = Partial<Record<keyof FormState | '_form', string>>;

type FormState = {
  voteId: string;
  country: string;
  contribution: string;
  contactMethod: ContactMethod | '';
  contactId: string;
  xHandles: string;
  // honeypot — hidden from real users, attractive to naive bots
  url: string;
};

const initial: FormState = {
  voteId: '',
  country: '',
  contribution: '',
  contactMethod: '',
  contactId: '',
  xHandles: '',
  url: '',
};

export function WhitelistForm() {
  const [state, setState] = useState<FormState>(initial);
  const [errors, setErrors] = useState<Errors>({});
  const [busy, setBusy] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  function update<K extends keyof FormState>(key: K, value: FormState[K]) {
    setState((s) => ({ ...s, [key]: value }));
    // clear field-level error as the user types
    if (errors[key]) setErrors((e) => ({ ...e, [key]: undefined }));
  }

  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (busy) return;

    setErrors({});
    track('whitelist_form_submit_attempt');
    setBusy(true);

    try {
      const res = await fetch('/api/whitelist', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(state),
      });

      if (res.status === 204) {
        // honeypot path — pretend success
        setSubmitted(true);
        return;
      }

      const data = (await res.json().catch(() => null)) as
        | { ok: true }
        | { ok: false; errors?: Errors }
        | null;

      if (res.ok && data && 'ok' in data && data.ok) {
        track('whitelist_form_submit_success');
        setSubmitted(true);
        return;
      }

      track('whitelist_form_submit_error');
      setErrors(
        (data && 'errors' in data && data.errors) || {
          _form: 'Something went wrong. Please try again or reach us on Telegram.',
        },
      );
    } catch {
      track('whitelist_form_submit_error');
      setErrors({ _form: 'Network error. Please try again or reach us on Telegram.' });
    } finally {
      setBusy(false);
    }
  }

  if (submitted) {
    return (
      <div className="surface flex items-start gap-3 p-6 md:p-8">
        <CheckCircle2 className="h-6 w-6 shrink-0 text-success" aria-hidden />
        <div>
          <h3 className="font-display text-lg font-semibold text-ink">Thanks — we&apos;ve got your application.</h3>
          <p className="mt-2 text-sm leading-relaxed text-ink-muted text-pretty">
            We review applications manually and we&apos;ll be in touch via the contact you provided. If
            you don&apos;t hear back within a couple of weeks, ping us on Telegram with your validator&apos;s
            vote id and we&apos;ll surface your submission.
          </p>
        </div>
      </div>
    );
  }

  return (
    <form
      onSubmit={onSubmit}
      className="surface space-y-6 p-5 md:p-6"
      noValidate
      aria-busy={busy}
    >
      {/* honeypot — hidden from humans + assistive tech, visible to dumb bots */}
      <div aria-hidden="true" style={{ position: 'absolute', left: '-10000px', width: 1, height: 1, overflow: 'hidden' }}>
        <label htmlFor="wl-url">Website (leave blank)</label>
        <input
          id="wl-url"
          type="text"
          tabIndex={-1}
          autoComplete="off"
          value={state.url}
          onChange={(ev) => update('url', ev.target.value)}
        />
      </div>

      <Field
        label="Validator's vote id"
        htmlFor="wl-voteId"
        required
        error={errors.voteId}
      >
        <input
          id="wl-voteId"
          type="text"
          required
          value={state.voteId}
          onChange={(ev) => update('voteId', ev.target.value)}
          className={inputClass}
          autoComplete="off"
          spellCheck={false}
          maxLength={64}
        />
      </Field>

      <Field
        label="What country is the validator owner/operator located in?"
        htmlFor="wl-country"
        helper={`"Validator operator" meaning the party that ultimately benefits from the revenue generated by the validator.`}
        required
        error={errors.country}
      >
        <input
          id="wl-country"
          type="text"
          required
          value={state.country}
          onChange={(ev) => update('country', ev.target.value)}
          className={inputClass}
          autoComplete="country-name"
          maxLength={80}
        />
      </Field>

      <Field
        label="Please detail your contributions to the Solana ecosystem in your region"
        htmlFor="wl-contribution"
        required
        error={errors.contribution}
      >
        <textarea
          id="wl-contribution"
          required
          rows={6}
          value={state.contribution}
          onChange={(ev) => update('contribution', ev.target.value)}
          className={inputClass + ' resize-y min-h-32'}
          maxLength={4000}
        />
      </Field>

      <Field
        label="Best way to contact you?"
        htmlFor="wl-contactMethod"
        required
        error={errors.contactMethod}
      >
        <select
          id="wl-contactMethod"
          required
          value={state.contactMethod}
          onChange={(ev) => update('contactMethod', ev.target.value as ContactMethod)}
          className={inputClass + ' appearance-none'}
        >
          <option value="">— pick one —</option>
          {CONTACT_METHODS.map((m) => (
            <option key={m} value={m}>
              {m}
            </option>
          ))}
        </select>
      </Field>

      <Field
        label="Your best contact ID"
        htmlFor="wl-contactId"
        helper="Your email, Telegram username, X handle, or another way to reach you — matching whichever method you picked above."
        required
        error={errors.contactId}
      >
        <input
          id="wl-contactId"
          type="text"
          required
          value={state.contactId}
          onChange={(ev) => update('contactId', ev.target.value)}
          className={inputClass}
          autoComplete="off"
          spellCheck={false}
          maxLength={200}
        />
      </Field>

      <Field
        label="Your X handles related to this application"
        htmlFor="wl-xHandles"
        helper="It helps with your scoring because we can use it to verify you and your work. e.g. @x_username (multiple ok, comma-separated)."
        required
        error={errors.xHandles}
      >
        <input
          id="wl-xHandles"
          type="text"
          required
          value={state.xHandles}
          onChange={(ev) => update('xHandles', ev.target.value)}
          className={inputClass}
          autoComplete="off"
          spellCheck={false}
          maxLength={400}
        />
      </Field>

      {errors._form && (
        <p role="alert" className="text-sm text-red-600">
          {errors._form}
        </p>
      )}

      <div className="flex items-center justify-end gap-3 pt-2">
        <button
          type="submit"
          disabled={busy}
          className="inline-flex items-center justify-center rounded-full bg-sunrise-gradient px-6 py-3 text-sm font-medium text-white shadow-sm transition disabled:cursor-not-allowed disabled:opacity-60"
        >
          {busy ? 'Submitting…' : 'Submit application'}
        </button>
      </div>
    </form>
  );
}

const inputClass =
  'mt-2 w-full rounded-lg border border-ring bg-bg-muted/40 px-3 py-2.5 text-sm text-ink placeholder:text-ink-dim outline-none transition focus:ring-2 focus:ring-sunrise-500';

function Field({
  label,
  htmlFor,
  helper,
  required,
  error,
  children,
}: {
  label: string;
  htmlFor: string;
  helper?: string;
  required?: boolean;
  error?: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label htmlFor={htmlFor} className="block text-sm font-medium text-ink">
        {label}
        {required && <span className="ml-1 text-ink-dim">*</span>}
      </label>
      {helper && <p className="mt-1 text-xs text-ink-muted">{helper}</p>}
      {children}
      {error && (
        <p className="mt-2 text-xs text-red-600" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}
